---
# defaults file for k8s_worker
kube_proxy_version: 1.20.1
kubelet_version: 1.20.1
use_kube_proxy: true


containerd_version: 1.3.6
runc_version: v1.0.0-rc91

crictl_version: 1.18.0

kubelet_conf_dir: /var/lib/kubelet
kube_proxy_conf_dir: /var/lib/kube-proxy

cluster_name: hardway
kubernetes_public_address: hardway

kube_proxy_mode: ipvs
cluster_cidr: 10.200.0.0/16